import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/header/header";
import Footer from "@/components/layouts/footer/footer";
import { Quicksand } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });
export const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${quicksand.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
